[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
serverAddress = "trading.lucamanca.synology.me"
gatherUsageStats = false
